<?php

namespace Fuz\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FiddleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FiddleRepository extends EntityRepository
{
}
